version: "3.3"
services:
  web:
    build: "."
    container_name: "web"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - redis
    environment:
      - "REDIS_HOSTNAME=redis"
      - "REDIS_PORT=6379"
  redis:
    image: "redis:5.0.6"
    container_name: "redis"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
